"use client";

import { useMemo, useState } from "react";
import { Building2, Check, ChevronRight, Clock3, LocateFixed, MapPin, MessageCircle, PackageCheck, Recycle, Search, ShieldCheck, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type Point = { id:number; name:string; place:string; distance:string; kinds:string[]; pickup:boolean; minimum:string; hours:string; pin:string; color:string };
const points:Point[] = [
  {id:1,name:"EcoPonto Centro",place:"Centro · Belo Horizonte",distance:"0,8 km",kinds:["Eletrônicos","Baterias","Cabos"],pickup:true,minimum:"A partir de 10 itens ou 5 kg",hours:"Seg–Sex, 9h às 17h",pin:"left-[49%] top-[39%]",color:"#0d8a67"},
  {id:2,name:"ReTec BH",place:"Funcionários · Belo Horizonte",distance:"1,7 km",kinds:["Eletrônicos","Celulares"],pickup:true,minimum:"Empresas: a partir de 20 itens",hours:"Seg–Sex, 8h às 18h",pin:"left-[66%] top-[47%]",color:"#3873db"},
  {id:3,name:"Ponto Verde Savassi",place:"Savassi · Belo Horizonte",distance:"2,4 km",kinds:["Pilhas","Baterias","Celulares"],pickup:false,minimum:"Entrega no local",hours:"Todos os dias, 10h às 22h",pin:"left-[60%] top-[67%]",color:"#d68b24"},
  {id:4,name:"Circular Tecnologia",place:"Floresta · Belo Horizonte",distance:"3,1 km",kinds:["Computadores","Monitores","Cabos"],pickup:true,minimum:"A partir de 3 equipamentos",hours:"Seg–Sáb, 9h às 16h",pin:"left-[30%] top-[45%]",color:"#7a5bd6"},
];
const filters=["Todos","Eletrônicos","Baterias","Celulares","Computadores"];

export default function Home() {
  const [filter,setFilter]=useState("Todos");
  const [query,setQuery]=useState("");
  const [onlyPickup,setOnlyPickup]=useState(false);
  const [selected,setSelected]=useState(points[0]);
  const [chatOpen,setChatOpen]=useState(false);
  const [registerOpen,setRegisterOpen]=useState(false);
  const [sent,setSent]=useState(false);
  const shown=useMemo(()=>points.filter(p=>(filter==="Todos"||p.kinds.includes(filter))&&`${p.name} ${p.place} ${p.kinds.join(" ")}`.toLowerCase().includes(query.toLowerCase())&&(!onlyPickup||p.pickup)),[filter,query,onlyPickup]);

  return (
    <main className="min-h-screen bg-[#f3f7f5] text-[#15382f]">
      <header className="sticky top-0 z-30 border-b border-[#dce9e3] bg-[#f9fcfa]/95 backdrop-blur">
        <div className="mx-auto flex h-[76px] max-w-[1500px] items-center justify-between px-5 md:px-9">
          <a href="#inicio" className="flex items-center gap-3 font-black tracking-tight text-[#104f40]"><span className="grid size-10 place-items-center rounded-2xl bg-[#0b8a68] text-white"><Recycle size={23}/></span><span className="text-xl">descarte<span className="text-[#0b8a68]">certo</span></span></a>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-[#4d6c62] md:flex"><a className="text-[#156c56]" href="#buscar">Encontrar ponto</a><a href="#como-funciona">Como funciona</a><button onClick={()=>setRegisterOpen(true)}>Para receptores</button></nav>
          <div className="flex gap-2"><Button variant="ghost" className="hidden text-[#37665a] sm:inline-flex">Entrar</Button><Button onClick={()=>setRegisterOpen(true)} className="rounded-xl bg-[#0b765d] text-white hover:bg-[#085e4a]">Cadastrar receptor</Button></div>
        </div>
      </header>

      <section id="inicio" className="mx-auto max-w-[1500px] px-5 pb-7 pt-8 md:px-9 md:pt-11">
        <div className="mb-7 flex flex-col justify-between gap-4 lg:flex-row lg:items-end">
          <div><p className="mb-2 flex items-center gap-2 text-sm font-bold text-[#0d8a67]"><span className="size-2 rounded-full bg-[#0d8a67]"/> DESCARTE RESPONSÁVEL, PERTO DE VOCÊ</p><h1 className="max-w-2xl text-3xl font-black leading-[1.05] tracking-[-.04em] text-[#123f34] md:text-5xl">Dê o destino certo<br className="hidden md:block"/> ao que não serve mais.</h1></div>
          <p className="max-w-sm text-base leading-6 text-[#5b756c]">Encontre receptores de eletrônicos e baterias, veja as condições de coleta e fale direto com quem vai receber.</p>
        </div>
        <div id="buscar" className="rounded-[28px] border border-[#d7e7df] bg-white p-3 shadow-[0_18px_50px_rgba(16,79,64,.07)] md:p-4">
          <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto]">
            <label className="flex h-14 items-center gap-3 rounded-2xl bg-[#f1f7f4] px-4 text-[#4d6c62]"><Search size={20} className="text-[#0a8766]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por bairro, cidade ou material" className="min-w-0 flex-1 bg-transparent text-base font-medium outline-none placeholder:text-[#8ba69b]"/><Button type="button" variant="ghost" size="sm" className="hidden text-[#0a8766] sm:flex"><LocateFixed size={18}/> Usar localização</Button></label>
            <div className="flex items-center gap-2 overflow-x-auto pb-1 lg:pb-0">{filters.map(item=><button key={item} onClick={()=>setFilter(item)} className={`shrink-0 rounded-xl px-3.5 py-3 text-sm font-bold transition ${filter===item?"bg-[#0b765d] text-white shadow-md":"bg-[#f1f7f4] text-[#45675c] hover:bg-[#e5f1eb]"}`}>{item}</button>)}</div>
          </div>
          <label className="mt-3 flex w-fit cursor-pointer items-center gap-2 text-sm font-semibold text-[#4a6c61]"><input checked={onlyPickup} onChange={e=>setOnlyPickup(e.target.checked)} type="checkbox" className="size-4 accent-[#0b765d]"/> Mostrar apenas quem busca no local</label>
        </div>
      </section>

      <section className="mx-auto grid max-w-[1500px] gap-5 px-5 pb-10 md:px-9 xl:grid-cols-[410px_minmax(0,1fr)]">
        <aside className="order-2 xl:order-1">
          <div className="mb-4 flex items-baseline justify-between"><h2 className="text-lg font-black text-[#174438]">Pontos próximos</h2><span className="text-sm font-semibold text-[#638078]">{shown.length} encontrados</span></div>
          <div className="max-h-[575px] space-y-3 overflow-y-auto pr-1">
            {shown.map(point=><button key={point.id} onClick={()=>setSelected(point)} className={`w-full rounded-2xl border p-4 text-left transition ${selected.id===point.id?"border-[#0b8a68] bg-[#ecf9f4] ring-1 ring-[#0b8a68]":"border-[#dfeae5] bg-white hover:border-[#a8d7c6]"}`}><div className="flex gap-3"><span className="mt-0.5 grid size-10 shrink-0 place-items-center rounded-xl bg-[#eaf5f0] text-[#0a8766]"><MapPin size={20}/></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h3 className="font-extrabold text-[#1d4a3e]">{point.name}</h3><span className="shrink-0 text-xs font-bold text-[#0a8766]">{point.distance}</span></div><p className="mt-1 text-sm text-[#607b72]">{point.place}</p><div className="mt-3 flex flex-wrap gap-1.5">{point.kinds.slice(0,3).map(kind=><span key={kind} className="rounded-md bg-[#dff1e9] px-2 py-1 text-xs font-bold text-[#367060]">{kind}</span>)}{point.pickup&&<span className="rounded-md bg-[#eef2ff] px-2 py-1 text-xs font-bold text-[#5262a2]"><Truck className="mr-1 inline" size={12}/>Coleta</span>}</div></div></div></button>)}
            {!shown.length&&<div className="rounded-2xl border border-dashed border-[#bbd7cb] bg-white p-8 text-center text-[#638078]"><Search className="mx-auto mb-3 text-[#74af9a]"/><p className="font-bold">Nenhum ponto encontrado</p><p className="mt-1 text-sm">Tente outro material ou remova os filtros.</p></div>}
          </div>
        </aside>
        <div className="order-1 overflow-hidden rounded-[26px] border border-[#dbeae3] bg-[#dcefe6] shadow-[0_18px_50px_rgba(16,79,64,.07)] xl:order-2">
          <div className="relative min-h-[430px] overflow-hidden bg-[#d9ede3] p-5 sm:min-h-[575px]">
            <div className="absolute inset-0 opacity-70" style={{backgroundImage:"linear-gradient(31deg,transparent 47%,#b7d8c8 48%,#b7d8c8 49%,transparent 50%),linear-gradient(116deg,transparent 46%,#c4dfd1 47%,#c4dfd1 49%,transparent 50%)",backgroundSize:"260px 190px,330px 240px"}}/>
            <div className="absolute left-[7%] top-[13%] size-28 rounded-full border-[18px] border-[#b4dac7]/50"/><div className="absolute bottom-[7%] right-[6%] size-44 rounded-full border-[24px] border-[#b4dac7]/40"/>
            <div className="relative z-10 flex items-start justify-between"><div className="rounded-xl bg-white/90 px-3 py-2 text-sm font-bold text-[#345f51] shadow-sm"><MapPin className="mr-1 inline text-[#0b8a68]" size={17}/> Belo Horizonte, MG</div><button className="grid size-10 place-items-center rounded-xl bg-white text-[#0a8766] shadow-sm" aria-label="Centralizar mapa"><LocateFixed size={20}/></button></div>
            {shown.map(point=><button key={point.id} onClick={()=>setSelected(point)} className={`absolute z-10 -translate-x-1/2 -translate-y-full rounded-full border-4 border-white p-2 text-white shadow-lg transition hover:scale-110 ${point.pin} ${selected.id===point.id?"ring-4 ring-[#133f34]/20 scale-110":""}`} style={{background:point.color}} aria-label={`Ver ${point.name}`}><MapPin size={22} fill="currentColor"/></button>)}
            <div className="absolute bottom-4 left-4 right-4 z-10 max-w-xl rounded-2xl border border-white/80 bg-white/95 p-4 shadow-xl backdrop-blur sm:bottom-6 sm:left-6 sm:right-auto sm:w-[min(430px,calc(100%-48px))]">
              <div className="flex gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#e3f5ed] text-[#0a8766]"><Recycle size={23}/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wide text-[#0c8967]">{selected.distance} de você</p><h2 className="font-black text-[#174438]">{selected.name}</h2></div><span className="rounded-lg bg-[#e4f5ed] px-2 py-1 text-xs font-black text-[#0a8766]">Aberto</span></div><p className="mt-1 text-sm text-[#58756a]">{selected.place}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs font-semibold text-[#55756a]"><span className="flex items-center gap-1"><Clock3 size={14}/>{selected.hours}</span><span className="flex items-center gap-1">{selected.pickup?<Truck size={14}/>:<PackageCheck size={14}/>}{selected.pickup?"Faz coleta":"Entrega local"}</span></div><Button onClick={()=>setChatOpen(true)} className="mt-4 h-10 w-full rounded-xl bg-[#0b765d] text-white hover:bg-[#085e4a]"><MessageCircle size={17}/> Conversar com receptor</Button></div></div>
            </div>
          </div>
        </div>
      </section>
      <section id="como-funciona" className="border-y border-[#dbe8e2] bg-white"><div className="mx-auto max-w-[1500px] px-5 py-10 md:px-9"><p className="text-sm font-black uppercase tracking-[.12em] text-[#0a8766]">SIMPLES E RASTREÁVEL</p><div className="mt-5 grid gap-6 md:grid-cols-3">{[[Search,"Busque perto de você","Filtre por material e veja os receptores na região."],[Truck,"Confira a coleta","Compare condições, quantidade mínima e horários."],[MessageCircle,"Combine pelo chat","Entre para conversar com o receptor de forma segura."]].map(([Icon,title,text],index)=>{const I=Icon as typeof Search;return <div key={String(title)} className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#e5f5ee] text-[#0a8766]"><I size={22}/></span><div><p className="text-xs font-black text-[#88a096]">0{index+1}</p><h3 className="font-black text-[#1b493c]">{String(title)}</h3><p className="mt-1 text-sm leading-5 text-[#607970]">{String(text)}</p></div></div>})}</div></div></section>
      <footer className="mx-auto flex max-w-[1500px] flex-col gap-4 px-5 py-7 text-sm text-[#68837a] md:flex-row md:items-center md:justify-between md:px-9"><div className="flex items-center gap-2 font-bold text-[#315e51]"><Recycle size={18} className="text-[#0a8766]"/> descartecerto</div><p>Uma ponte entre quem descarta e quem dá um novo destino.</p><span className="flex items-center gap-1"><ShieldCheck size={16}/> Dados tratados com responsabilidade</span></footer>
      <Dialog open={chatOpen} onOpenChange={setChatOpen}><DialogContent className="max-w-md rounded-3xl border-[#d7e8df] p-7"><DialogHeader><span className="mb-2 grid size-12 place-items-center rounded-2xl bg-[#e3f6ee] text-[#0b8867]"><MessageCircle size={25}/></span><DialogTitle className="text-2xl font-black text-[#184538]">Converse com {selected.name}</DialogTitle><DialogDescription className="leading-6 text-[#5e776e]">Para manter a conversa segura e registrar seu pedido de coleta, entre ou crie sua conta.</DialogDescription></DialogHeader><div className="mt-2 rounded-xl bg-[#f1f8f4] p-4 text-sm text-[#4e6e63]"><p className="font-black text-[#256351]">Coleta deste receptor</p><p className="mt-1"><Truck className="mr-1 inline text-[#0b8a68]" size={15}/> {selected.pickup?selected.minimum:"Este ponto recebe apenas entregas presenciais."}</p></div><Button className="mt-2 h-11 rounded-xl bg-[#0b765d] text-white hover:bg-[#085e4a]">Entrar para abrir o chat <ChevronRight size={18}/></Button><button className="text-sm font-bold text-[#0b765d] underline underline-offset-4">Ainda não tenho conta — criar cadastro</button></DialogContent></Dialog>
      <Dialog open={registerOpen} onOpenChange={open=>{setRegisterOpen(open);if(!open)setSent(false)}}><DialogContent className="max-h-[90vh] max-w-lg overflow-y-auto rounded-3xl border-[#d7e8df] p-7"><DialogHeader><span className="mb-2 grid size-12 place-items-center rounded-2xl bg-[#e3f6ee] text-[#0b8867]"><Building2 size={25}/></span><DialogTitle className="text-2xl font-black text-[#184538]">Seja um receptor parceiro</DialogTitle><DialogDescription className="leading-6 text-[#5e776e]">Cadastre sua organização para receber pedidos de descarte e coleta.</DialogDescription></DialogHeader>{sent?<div className="py-8 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-[#ddf5e9] text-[#087c5c]"><Check size={32}/></span><h3 className="mt-4 text-xl font-black text-[#1b493c]">Cadastro enviado!</h3><p className="mt-2 text-sm leading-6 text-[#5d776d]">Vamos confirmar os dados e, depois da aprovação, sua empresa poderá aparecer no mapa e receber mensagens.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="mt-2 space-y-4"><label className="block text-sm font-bold text-[#3d6659]">Nome da organização<input required placeholder="Ex.: Recicla Tech Ltda." className="mt-1.5 h-11 w-full rounded-xl border border-[#d3e4dc] bg-[#fbfefc] px-3 text-base font-medium outline-none focus:border-[#0b8a68]"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold text-[#3d6659]">E-mail<input type="email" required placeholder="contato@empresa.com" className="mt-1.5 h-11 w-full rounded-xl border border-[#d3e4dc] bg-[#fbfefc] px-3 outline-none focus:border-[#0b8a68]"/></label><label className="block text-sm font-bold text-[#3d6659]">WhatsApp<input required placeholder="(31) 99999-9999" className="mt-1.5 h-11 w-full rounded-xl border border-[#d3e4dc] bg-[#fbfefc] px-3 outline-none focus:border-[#0b8a68]"/></label></div><label className="block text-sm font-bold text-[#3d6659]">Endereço do ponto de recebimento<input required placeholder="Rua, número, bairro e cidade" className="mt-1.5 h-11 w-full rounded-xl border border-[#d3e4dc] bg-[#fbfefc] px-3 outline-none focus:border-[#0b8a68]"/></label><label className="flex cursor-pointer gap-3 rounded-xl bg-[#f1f8f4] p-3 text-sm leading-5 text-[#4b6d61]"><input required type="checkbox" className="mt-1 size-4 accent-[#0b765d]"/><span>Confirmo que as informações são verdadeiras e aceito o termo de responsabilidade para recebimento e destinação ambientalmente adequada.</span></label><Button type="submit" className="h-11 w-full rounded-xl bg-[#0b765d] text-white hover:bg-[#085e4a]">Enviar cadastro <ChevronRight size={17}/></Button></form>}</DialogContent></Dialog>
    </main>
  );
}
